name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (attendance)
        run: npm install
        working-directory: attendance

      - name: Build attendance
        run: npm run build
        working-directory: attendance

      - name: Install dependencies (employees)
        run: npm install
        working-directory: employees

      - name: Build employees
        run: npm run build
        working-directory: employees

      - name: Install dependencies (payroll)
        run: npm install
        working-directory: payroll

      - name: Build payroll
        run: npm run build
        working-directory: payroll

      - name: Install dependencies (tax)
        run: npm install
        working-directory: tax

      - name: Build tax
        run: npm run build
        working-directory: tax